apiVersion: v1
kind: Service
metadata:
  name: test-svc
  labels:
    app: aries-depl
spec:
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 31111
  selector:
    app: aries-depl